# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: trivy-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/trivy"
  persistentVolumeReclaimPolicy: Retain
